"""enable pgvector extension

Revision ID: 202607290001
Revises:
Create Date: 2026-07-29

Extension management is never autogenerated by Alembic — it has no
concept of CREATE EXTENSION, so this is always a hand-written migration.
Every other migration in this project can assume `vector` already exists.
"""
from collections.abc import Sequence

from alembic import op

revision: str = "202607290001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")
